theme = "onelight"

[editor]
color-modes = true
cursorline = true
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.insert.j]
k = "normal_mode"
