[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "html"
roots = [".git"]
language-servers = ["emmet-lsp"]

[[language]]
name = "css"
roots = [".git"]
language-servers = ["emmet-lsp"]

[[language]]
name = "erb"
file-types = ["ecr"]
roots = [".git"]
scope = "scope.ecr"
language-servers = ["emmet-lsp"]
